Class HC_ArmorBonus : BasicArmorBonus
{
	Default {
  Radius 20;
  Height 16;
  Inventory.PickupMessage "Picked up an armor bonus.";
  Inventory.Icon "ARMICO1";
  Inventory.PickupSound "ArmorBonus";
  Armor.SavePercent 50;//33.335;
  Armor.SaveAmount 1;
  Armor.MaxSaveAmount 200;
  +COUNTITEM;
  +INVENTORY.ALWAYSPICKUP;
  }
  States
  {
  Spawn:
    ARMB A 10;
	ARMB BCD 1;
	ARMB E 10;
	ARMB DCB 1;
    Loop;
  }
}
