Class HC_BulletPuff : Actor
{	
	Default
	{
		+NOBLOCKMAP
		+NOGRAVITY
		+ALLOWPARTICLES
		+RANDOMIZE
		+ZDOOMTRANS
		+ROLLSPRITE
		+FORCEXYBILLBOARD
		Decal "BulletChip";
		Renderstyle "Add";
		radius 2;
		Height 2;
		Scale 1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0
		{
			for (int i = random(1,2); i > 0; i--)
			{
				A_SpawnItemEx("RocketSmokeTrail",0,0,0,frandom(-1,1),frandom(-1,1),frandom(-1,1));
			}
		}
		
		TNT1 AAAAA 0 A_SpawnItemEx("HC_PuffParticlesBase",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10));
		TNT1 AA 0 A_SpawnItemEx("HC_PuffParticlesBig",0,0,0,frandom(-15,15),frandom(-15,15),frandom(-15,15));
		
		TNT1 A 0 A_StartSound("BulletImpactMedium",0,CHANF_DEFAULT,0.5);
		
		TNT1 A 0 A_SetRoll(random(0,359));
		
		HPUF ABCD 1 Bright;
		Stop;
	}
}



class HC_PuffParticlesBase: HC_FXClass {
	Default {
		Scale 0.6;
		Renderstyle "Add";
		
		bouncefactor 0.5;
		wallbouncefactor 0.4;
		bouncecount 5;
		bouncetype "Doom";
		
		radius 2;
		Height 2;
		
		projectile;
		-NOGRAVITY
		-NOBLOCKMAP
		+NOTELEPORT
		+THRUACTORS
		+DROPOFF
		+FLOORCLIP
		-BOUNCEONACTORS
		+FORCEXYBILLBOARD
	}

	States {
		Spawn:
			PUFF A Random(2,4) BRIGHT;
		Death:
			TNT1 A 1;
			Stop;
	}
}

class HC_PuffParticlesBig: HC_FXClass {
	Default {
		Scale 0.8;
		Renderstyle "Add";
		
		bouncefactor 0.5;
		wallbouncefactor 0.4;
		bouncecount 5;
		bouncetype "Doom";
		
		radius 2;
		Height 2;
		
		projectile;
		-NOGRAVITY
		-NOBLOCKMAP
		+NOTELEPORT
		+THRUACTORS
		+DROPOFF
		+FLOORCLIP
		-BOUNCEONACTORS
		+FORCEXYBILLBOARD
	}

	States {
		Spawn:
			PUFF A Random(4,8) BRIGHT;
		Death:
			TNT1 A 1;
			Stop;
	}
}

class HC_PuffParticlesHUGE: HC_FXClass {
	Default {
		Scale 0.9;
		Renderstyle "Add";
		
		bouncefactor 0.5;
		wallbouncefactor 0.4;
		bouncecount 5;
		bouncetype "Doom";
		
		radius 2;
		Height 2;
		
		projectile;
		-NOGRAVITY
		-NOBLOCKMAP
		+NOTELEPORT
		+THRUACTORS
		+DROPOFF
		+FLOORCLIP
		-BOUNCEONACTORS
		+FORCEXYBILLBOARD
	}

	States {
		Spawn:
			PUFF A Random(25,35) BRIGHT;
		Death:
			TNT1 A 1;
			Stop;
	}
}



Class HC_GaussPuff : BulletPuff
{	
	Default
	{
		Decal "Scorch";
		DamageType "PlayerGauss";
		
		RenderStyle "Add";
		Alpha 0.75;
		
		+NODAMAGETHRUST
		+ALWAYSPUFF
		+ZDOOMTRANS
	}
	States
	{
	Spawn:
		TNT1 A 0;
		//TNT1 A 0 A_Explode(32,0,XF_NOTMISSILE);
		TNT1 A 0 A_StartSound("GaussCannonHit",CHAN_WEAPON,0,.6);
		
		TNT1 A 0 A_Explode(256);
		
		TNT1 A 0
		{
			for (int i = random(5,10); i > 0; i--)
			{
				A_SpawnItemEx("RocketSmokeTrail",0,0,0,frandom(-20,20),frandom(-20,20),frandom(-20,20));
			}
		}
		
		TNT1 A 0
		{
			for (int i = random(1,3); i > 0; i--)
			{
				A_SpawnItemEx("ExplosionShockWave",0,0,0,0,0,0);
			}
		}
		
		TNT1 A 0
		{
			for (int i = random(7,12); i > 0; i--)
			{
				A_SpawnItemEx("HC_PlasmaBallFX",0,0,0,frandom(-20,20),frandom(-20,20),frandom(-20,20));
			}
		}
		
		XGCE ABBCCC 1 Bright;
		Stop;

	}
}

Class HC_SeigeGaussPuff : BulletPuff
{	
	Default
	{
	Decal "Scorch";
	DamageType "PlayerGauss";
	
	RenderStyle "Add";
	Alpha 0.75;
	
	+NODAMAGETHRUST
	+ALWAYSPUFF
	+ZDOOMTRANS
	}
	States
	{
	Spawn:
		TNT1 A 0;
		//TNT1 A 0 A_Explode(32,0,XF_NOTMISSILE);
		TNT1 A 0 A_StartSound("GaussCannonHit",CHAN_WEAPON,0,.6);
		
		TNT1 A 0 A_Explode(256);
		
		TNT1 A 0
		{
			for (int i = random(15,20); i > 0; i--)
			{
				A_SpawnItemEx("RocketSmokeTrail",0,0,0,frandom(-25,25),frandom(-25,25),frandom(-25,25));
			}
		}
		
		TNT1 A 0
		{
			for (int i = random(2,8); i > 0; i--)
			{
				A_SpawnItemEx("ExplosiveDebris",0,0,0,frandom(-30,30),frandom(-30,30),frandom(-30,30));
			}
		}
		
		TNT1 A 0
		{
			for (int i = random(1,3); i > 0; i--)
			{
				A_SpawnItemEx("BIGExplosionShockWave",0,0,0,0,0,0);
			}
		}
		
		TNT1 A 0
		{
			for (int i = random(10,20); i > 0; i--)
			{
				A_SpawnItemEx("HC_PlasmaBallFX",0,0,0,frandom(-25,25),frandom(-25,25),frandom(-25,25));
			}
		}
		
		XGCE ABBCCC 1 Bright;
		Stop;

	}
}

