//BLUE PLASMA

class HC_PlasmaBallFX : HC_FXClass
{
	
	double PBFXScale;
	
	Default
	{
		Radius 8;
		Height 8;
		Speed 270;
		
		RenderStyle "Add";
		Alpha 0.75;
		
		+NOBLOCKMAP
		//+NOCLIP
		+NOGRAVITY
		+DONTSPLASH
		+NOTELEPORT
		+FORCEXYBILLBOARD
		+RANDOMIZE
		+ZDOOMTRANS
	}
	States
	{
 	Spawn:
		TNT1 A 0;
		TNT1 A 0 {invoker.PBFXScale++;}
		TNT1 A 0;
	Fly:
		PLSS A 1 Bright {A_SetScale(invoker.PBFXScale = invoker.PBFXScale - 0.075); A_FadeOut(0.075);}
		PLSS A 1 Bright {A_SetScale(invoker.PBFXScale = invoker.PBFXScale - 0.075); A_FadeOut(0.075);}
		PLSS A 1 Bright {A_SetScale(invoker.PBFXScale = invoker.PBFXScale - 0.075); A_FadeOut(0.075);}
		
		PLSS B 1 Bright {A_SetScale(invoker.PBFXScale = invoker.PBFXScale - 0.075); A_FadeOut(0.075);}
		PLSS B 1 Bright {A_SetScale(invoker.PBFXScale = invoker.PBFXScale - 0.075); A_FadeOut(0.075);}
		PLSS B 1 Bright {A_SetScale(invoker.PBFXScale = invoker.PBFXScale - 0.075); A_FadeOut(0.075);}
		Loop;
	}
}
