//BLUE PLASMA

class HC_PlasmaBall : Actor
{
	Default
	{
		Radius 8;
		Height 8;
		Speed 140;
 		DamageFunction 45;//10;
		
		RenderStyle "Add";
		Alpha 0.75;
		
		//SeeSound "weapons/plasmaf";
		
		DeathSound "weapons/plasmax";
		Obituary "$OB_MPPLASMARIFLE";
		Decal "PlasmaScorch";
		
		Projectile;
		+RANDOMIZE
		+ZDOOMTRANS
	}
	States
	{
 	Spawn:
		PLSS A 1 Bright A_SpawnItemEx("HC_PlasmaBallFX");
		PLSS A 1 Bright A_SpawnItemEx("HC_PlasmaBallFX");
		PLSS A 1 Bright A_SpawnItemEx("HC_PlasmaBallFX");
		
		PLSS B 1 Bright A_SpawnItemEx("HC_PlasmaBallFX");
		PLSS B 1 Bright A_SpawnItemEx("HC_PlasmaBallFX");
		PLSS B 1 Bright A_SpawnItemEx("HC_PlasmaBallFX");
		Loop;
	Death:
		PLSE ABC 1;
		TNT1 A 0
		{
			for (int i = random(6,8); i > 0; i--)
			{
				A_SpawnItemEx("RocketSmokeTrail",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10));
			}
		}
		
		TNT1 A 0
		{
			for (int i = random(2,4); i > 0; i--)
			{
				A_SpawnItemEx("HC_PlasmaBallFX",0,0,0,frandom(-10,10),frandom(-10,10),frandom(-10,10));
			}
		}
		PLSE DDEEE 1 Bright;
		Stop;
	}
}

class HC_PlasmaBallFX : HC_FXClass
{
	
	double PBFXScale;
	
	Default
	{
		Radius 8;
		Height 8;
		Speed 270;
		
		RenderStyle "Add";
		Alpha 0.75;
		
		+NOBLOCKMAP
		//+NOCLIP
		+NOGRAVITY
		+DONTSPLASH
		+NOTELEPORT
		+FORCEXYBILLBOARD
		+RANDOMIZE
		+ZDOOMTRANS
	}
	States
	{
 	Spawn:
		TNT1 A 0;
		TNT1 A 0 {invoker.PBFXScale++;}
		TNT1 A 0;
	Fly:
		PLSS A 1 Bright {A_SetScale(invoker.PBFXScale = invoker.PBFXScale - 0.075); A_FadeOut(0.075);}
		PLSS A 1 Bright {A_SetScale(invoker.PBFXScale = invoker.PBFXScale - 0.075); A_FadeOut(0.075);}
		PLSS A 1 Bright {A_SetScale(invoker.PBFXScale = invoker.PBFXScale - 0.075); A_FadeOut(0.075);}
		
		PLSS B 1 Bright {A_SetScale(invoker.PBFXScale = invoker.PBFXScale - 0.075); A_FadeOut(0.075);}
		PLSS B 1 Bright {A_SetScale(invoker.PBFXScale = invoker.PBFXScale - 0.075); A_FadeOut(0.075);}
		PLSS B 1 Bright {A_SetScale(invoker.PBFXScale = invoker.PBFXScale - 0.075); A_FadeOut(0.075);}
		Loop;
	}
}
